export type FieldType = 'string' | 'number' | 'boolean' | 'enum' | 'array' | 'object' | 'model-select' | 'model-fallbacks';

export interface FieldDef {
  path: string;
  label: string;
  help: string;
  type: FieldType;
  options?: string[];
  sensitive?: boolean;
  defaultValue?: unknown;
  /** Recommended value — may differ from defaultValue when a safer/better option exists */
  recommended?: unknown;
  /** Why this value is recommended (shown as a contextual tip) */
  recommendedReason?: string;
  min?: number;
  max?: number;
  placeholder?: string;
  required?: boolean;
  optionDescriptions?: Record<string, string>;
  examples?: string[];
  docUrl?: string;
}

export interface SectionDef {
  id: string;
  label: string;
  description: string;
  icon: string;
  fields: FieldDef[];
}

export const SECTIONS: SectionDef[] = [
  {
    id: 'update',
    label: 'Update',
    description: 'Control how OpenClaw checks for and applies updates.',
    icon: '🔄',
    fields: [
      {
        path: 'update.channel',
        label: 'Update Channel',
        help: 'Release channel to track for updates.',
        type: 'enum',
        options: ['stable', 'beta', 'dev'],
        defaultValue: 'stable',
        recommended: 'stable',
        recommendedReason: 'Stable is production-ready and vetted by the OpenClaw team. Beta/dev can introduce breaking changes or unpatched security issues.',
        optionDescriptions: {
          stable: 'Production-ready releases. Recommended for most users. Tagged as vYYYY.M.D on npm.',
          beta: 'Prerelease builds with new features being tested. May have minor issues. Tagged as beta on npm.',
          dev: 'Moving head of main branch. Latest code but may be unstable. Use only for development/testing.',
        },
      },
      {
        path: 'update.checkOnStart',
        label: 'Check on Startup',
        help: 'Automatically check for updates when the gateway starts.',
        type: 'boolean',
        defaultValue: true,
        recommended: true,
        recommendedReason: 'Ensures you always run with the latest security patches and bug fixes on startup.',
      },
    ],
  },
  {
    id: 'logging',
    label: 'Logging',
    description: 'Configure log verbosity and output format.',
    icon: '📋',
    fields: [
      {
        path: 'logging.level',
        label: 'Log Level',
        help: 'Global log verbosity level.',
        type: 'enum',
        options: ['silent', 'fatal', 'error', 'warn', 'info', 'debug', 'trace'],
        defaultValue: 'info',
        recommended: 'info',
        recommendedReason: 'info gives you full operational visibility without flooding storage. Use debug only when actively diagnosing a problem.',
        optionDescriptions: {
          silent: 'No log output at all. Use when you want zero noise.',
          fatal: 'Only unrecoverable crashes. Gateway will exit after these.',
          error: "Errors that need attention but don't crash the gateway.",
          warn: 'Warnings about suboptimal configuration or recoverable issues.',
          info: 'Normal operational messages. Recommended for production.',
          debug: 'Detailed internal flow. Use when troubleshooting issues.',
          trace: 'Maximum verbosity — every internal event. Very noisy.',
        },
      },
      {
        path: 'logging.consoleLevel',
        label: 'Console Log Level',
        help: 'Log verbosity level for console output.',
        type: 'enum',
        options: ['silent', 'fatal', 'error', 'warn', 'info', 'debug', 'trace'],
        defaultValue: 'info',
        optionDescriptions: {
          silent: 'No log output at all. Use when you want zero noise.',
          fatal: 'Only unrecoverable crashes. Gateway will exit after these.',
          error: "Errors that need attention but don't crash the gateway.",
          warn: 'Warnings about suboptimal configuration or recoverable issues.',
          info: 'Normal operational messages. Recommended for production.',
          debug: 'Detailed internal flow. Use when troubleshooting issues.',
          trace: 'Maximum verbosity — every internal event. Very noisy.',
        },
      },
      {
        path: 'logging.consoleStyle',
        label: 'Console Style',
        help: 'Output format for console logs.',
        type: 'enum',
        options: ['pretty', 'compact', 'json'],
        defaultValue: 'pretty',
        optionDescriptions: {
          pretty: 'Human-readable colored output with icons. Best for terminal use.',
          compact: 'One-line per event, less color. Good for log aggregators.',
          json: 'Machine-readable NDJSON. Best for log parsing tools (e.g. jq, Datadog).',
        },
      },
    ],
  },
  {
    id: 'gateway',
    label: 'Gateway',
    description: 'Configure the OpenClaw gateway server — port, authentication, and network binding.',
    icon: '🌐',
    fields: [
      {
        path: 'gateway.port',
        label: 'Port',
        help: 'Port the gateway HTTP/WebSocket server listens on.',
        type: 'number',
        min: 1,
        max: 65535,
        defaultValue: 3000,
        examples: ['18789'],
      },
      {
        path: 'gateway.mode',
        label: 'Gateway Mode',
        help: 'Whether this gateway operates locally or as a remote endpoint.',
        type: 'enum',
        options: ['local', 'remote'],
        defaultValue: 'local',
        optionDescriptions: {
          local: 'Gateway runs locally on this machine. All agent execution is local. Default and most common.',
          remote: 'Connect to a remote gateway instance. Use when running the agent on a separate server/VPS.',
        },
      },
      {
        path: 'gateway.bind',
        label: 'Network Binding',
        help: 'Which network interface the gateway binds to.',
        type: 'enum',
        options: ['auto', 'lan', 'loopback', 'custom', 'tailnet'],
        defaultValue: 'auto',
        recommended: 'auto',
        recommendedReason: 'auto picks the safest binding for your setup automatically. Only override if you need explicit LAN/Tailscale exposure.',
        optionDescriptions: {
          auto: 'Automatically selects the best binding based on your config (loopback if no tailscale, lan if tailscale serve).',
          loopback: 'Only accessible from this machine (127.0.0.1). Most secure for local use.',
          lan: 'Accessible from your local network. Required if other devices on your LAN need to reach the gateway.',
          custom: 'Bind to a specific IP address. Set gateway.bindAddress for the actual IP.',
          tailnet: 'Bind to your Tailscale IP only. Accessible from your tailnet but not the public internet.',
        },
      },
      {
        path: 'gateway.auth.mode',
        label: 'Auth Mode',
        help: 'Authentication mechanism for gateway connections.',
        type: 'enum',
        options: ['token', 'password'],
        defaultValue: 'token',
        optionDescriptions: {
          token: 'Static bearer token authentication. Set gateway.auth.token. Simple and secure for most setups.',
          password: 'Password-based auth. Required when using Tailscale Funnel (public internet exposure).',
        },
      },
      {
        path: 'gateway.auth.token',
        label: 'Gateway Token',
        help: 'Secret token used for token-based authentication.',
        type: 'string',
        sensitive: true,
        placeholder: 'Enter gateway token...',
      },
      {
        path: 'gateway.tailscale.mode',
        label: 'Tailscale Mode',
        help: 'How Tailscale integration operates.',
        type: 'enum',
        options: ['off', 'serve', 'funnel'],
        defaultValue: 'off',
        optionDescriptions: {
          off: 'Tailscale integration disabled. Gateway is only reachable via its bind address.',
          serve: 'Expose via Tailscale Serve — accessible only within your private tailnet. Zero public exposure.',
          funnel: 'Expose publicly via Tailscale Funnel (internet-accessible URL). Requires password auth mode.',
        },
      },
      {
        path: 'gateway.controlUi.enabled',
        label: 'Enable Control UI',
        help: 'Show the web-based control UI served by the gateway.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'gateway.reload.mode',
        label: 'Config Reload Mode',
        help: 'How the gateway reacts when the config file changes.',
        type: 'enum',
        options: ['off', 'restart', 'hot', 'hybrid'],
        defaultValue: 'hybrid',
        optionDescriptions: {
          off: 'Config file changes are ignored until you manually restart.',
          restart: 'Full gateway restart when config changes. Clean but causes brief downtime.',
          hot: 'Attempt to apply config changes without restarting. Faster but not all changes are hot-reloadable.',
          hybrid: 'Hot reload when possible; falls back to full restart for changes that require it. Recommended.',
        },
      },
    ],
  },
  {
    id: 'agents',
    label: 'Agents',
    description: 'Default settings for all agents — models, timeouts, sandboxing, and context pruning.',
    icon: '🤖',
    fields: [
      {
        path: 'agents.defaults.model.primary',
        label: 'Primary & Fallback Models',
        help: 'Select your primary model and drag-to-rank your fallback chain. OpenClaw tries each in order when the primary fails.',
        type: 'model-fallbacks',
      },
      {
        path: 'agents.defaults.workspace',
        label: 'Workspace Path',
        help: 'Default workspace directory for agents.',
        type: 'string',
        placeholder: '/path/to/workspace',
        examples: ['/home/user/.openclaw/workspace', '~/workspace'],
      },
      {
        path: 'agents.defaults.heartbeat.every',
        label: 'Heartbeat Interval',
        help: 'How often agents send a heartbeat poll (e.g. "30m", "1h").',
        type: 'string',
        placeholder: '30m',
        examples: ['30m', '1h', '2h'],
      },
      {
        path: 'agents.defaults.heartbeat.model',
        label: 'Heartbeat Model',
        help: 'Model used for heartbeat tasks (can be a smaller/cheaper model).',
        type: 'model-select',
        placeholder: 'ollama/llama3.2:1b',
      },
      {
        path: 'agents.defaults.maxConcurrent',
        label: 'Max Concurrent Agents',
        help: 'Maximum number of agents that can run simultaneously.',
        type: 'number',
        min: 1,
        max: 50,
        defaultValue: 5,
      },
      {
        path: 'agents.defaults.subagents.maxConcurrent',
        label: 'Max Concurrent Sub-Agents',
        help: 'Maximum number of sub-agents a single agent can spawn at once.',
        type: 'number',
        min: 1,
        max: 20,
        defaultValue: 3,
      },
      {
        path: 'agents.defaults.contextPruning.mode',
        label: 'Context Pruning Mode',
        help: 'When to prune old context from agent conversation history.',
        type: 'enum',
        options: ['off', 'cache-ttl'],
        defaultValue: 'off',
        recommended: 'cache-ttl',
        recommendedReason: 'cache-ttl keeps your context window lean and reduces token costs significantly. Off causes unbounded context growth that can hit model limits unexpectedly.',
        optionDescriptions: {
          off: 'No automatic context pruning. Context grows indefinitely (up to model limit).',
          'cache-ttl': 'Prune context entries older than the TTL to keep context window lean. Recommended.',
        },
      },
      {
        path: 'agents.defaults.contextPruning.ttl',
        label: 'Context Pruning TTL',
        help: 'Time-to-live for cached context before it is pruned (e.g. "2h").',
        type: 'string',
        placeholder: '2h',
        examples: ['15m', '30m', '1h'],
      },
      {
        path: 'agents.defaults.compaction.mode',
        label: 'Compaction Mode',
        help: 'Strategy for compacting long conversation histories.',
        type: 'enum',
        options: ['default', 'safeguard'],
        defaultValue: 'default',
        optionDescriptions: {
          default: 'Standard compaction — summarize old context when the window fills up.',
          safeguard: 'Conservative compaction — more aggressive summarization to prevent context overflow errors.',
        },
      },
      {
        path: 'agents.defaults.thinkingDefault',
        label: 'Thinking Budget Default',
        help: 'Default extended thinking budget for agents that support it.',
        type: 'enum',
        options: ['off', 'minimal', 'low', 'medium', 'high', 'xhigh'],
        defaultValue: 'off',
        optionDescriptions: {
          off: 'No extended thinking. Fastest and cheapest. Good for simple tasks.',
          minimal: 'Very brief reasoning step. Slightly better than off for light tasks.',
          low: 'Short reasoning. Balances cost and quality for moderately complex tasks.',
          medium: 'Moderate reasoning. Good for multi-step tasks and analysis.',
          high: 'Deep reasoning. Best for complex problem solving, debugging, research.',
          xhigh: 'Maximum extended thinking. Slowest and most expensive. Reserve for hardest tasks.',
        },
      },
      {
        path: 'agents.defaults.sandbox.mode',
        label: 'Sandbox Mode',
        help: 'Which agents run in a sandboxed environment.',
        type: 'enum',
        options: ['off', 'non-main', 'all'],
        defaultValue: 'off',
        recommended: 'non-main',
        recommendedReason: 'non-main sandboxes untrusted sub-agents and cron jobs (which run arbitrary code) while keeping your main chat agent unrestricted. "off" is a security risk if agents execute code.',
        optionDescriptions: {
          off: 'No sandboxing. Agent has direct access to your system. Fastest but least isolated.',
          'non-main': 'Sandbox sub-agents and cron-spawned agents, but not your main chat agent.',
          all: 'Sandbox all agents including the main session. Maximum isolation. Requires Docker.',
        },
      },
      {
        path: 'agents.defaults.sandbox.workspaceAccess',
        label: 'Sandbox Workspace Access',
        help: 'Filesystem access level for sandboxed agents.',
        type: 'enum',
        options: ['none', 'ro', 'rw'],
        defaultValue: 'ro',
        optionDescriptions: {
          none: 'Sandboxed agent cannot access your workspace at all.',
          ro: 'Sandboxed agent can read files from workspace but cannot write.',
          rw: 'Sandboxed agent has full read/write access to the workspace.',
        },
      },
      {
        path: 'agents.defaults.timeoutSeconds',
        label: 'Response Timeout (seconds)',
        help: 'Maximum seconds to wait for an agent LLM response before timing out.',
        type: 'number',
        min: 10,
        max: 600,
        defaultValue: 120,
      },
      {
        path: 'agents.defaults.typingMode',
        label: 'Typing Mode',
        help: 'When to show a "typing..." indicator in channels.',
        type: 'enum',
        options: ['never', 'instant', 'thinking', 'message'],
        defaultValue: 'message',
        optionDescriptions: {
          never: 'Never show a typing indicator. Replies just appear.',
          instant: 'Show typing indicator immediately when a message is received.',
          thinking: 'Show typing only while the agent is processing/reasoning.',
          message: 'Show typing indicator for the full duration until reply is sent.',
        },
      },
      {
        path: 'agents.defaults.verboseDefault',
        label: 'Verbose Mode Default',
        help: 'Default verbosity level for agent tool call output.',
        type: 'enum',
        options: ['off', 'on', 'full'],
        defaultValue: 'off',
        optionDescriptions: {
          off: 'Only show the final answer. No tool call details. Cleanest output.',
          on: 'Show tool calls and results inline. Good for debugging what the agent is doing.',
          full: 'Maximum verbosity — all intermediate steps, token counts, and reasoning.',
        },
      },
      {
        path: 'agents.defaults.elevatedDefault',
        label: 'Elevated Permissions Default',
        help: 'Default elevated permissions mode for agents.',
        type: 'enum',
        options: ['off', 'on', 'ask', 'full'],
        defaultValue: 'off',
        recommended: 'off',
        recommendedReason: 'Keep off unless specific tasks require host-level access. Elevated agents can run system commands — only enable per-session when needed.',
        optionDescriptions: {
          off: 'No elevated permissions. Agent runs with standard tool access.',
          on: 'Always run with elevated permissions. Allows host-level exec commands.',
          ask: 'Prompt the user for approval before executing elevated operations.',
          full: 'Full elevated mode with no restrictions. Use with extreme caution.',
        },
      },
    ],
  },
  {
    id: 'tools',
    label: 'Tools',
    description: 'Control which tools agents can use and how they interact with the web and shell.',
    icon: '🔧',
    fields: [
      {
        path: 'tools.profile',
        label: 'Tools Profile',
        help: 'Preset bundle of tools to enable for agents.',
        type: 'enum',
        options: ['minimal', 'coding', 'messaging', 'full'],
        defaultValue: 'full',
        optionDescriptions: {
          minimal: 'Only the most basic tools. Smallest attack surface. Good for simple chat bots.',
          coding: 'Adds file read/write, exec, and browser tools. Best for development workflows.',
          messaging: 'Adds messaging and channel management tools. Good for comms-focused agents.',
          full: 'All available tools enabled. Maximum capability. Review security implications.',
        },
      },
      {
        path: 'tools.exec.security',
        label: 'Exec Security',
        help: 'Security level for shell command execution.',
        type: 'enum',
        options: ['deny', 'allowlist', 'full'],
        defaultValue: 'allowlist',
        recommended: 'allowlist',
        recommendedReason: 'allowlist gives agents useful shell access while blocking dangerous commands not in your safeBins list. "full" is a significant attack surface if a prompt injection occurs.',
        optionDescriptions: {
          deny: 'Block all exec calls. Agent cannot run shell commands. Most secure.',
          allowlist: 'Only allow explicitly whitelisted binaries (tools.exec.safeBins). Balanced security.',
          full: 'Allow any shell command. Maximum power but higher risk. Only use in trusted environments.',
        },
      },
      {
        path: 'tools.exec.host',
        label: 'Exec Host',
        help: 'Where shell commands are executed.',
        type: 'enum',
        options: ['sandbox', 'gateway', 'node'],
        defaultValue: 'sandbox',
        recommended: 'sandbox',
        recommendedReason: 'sandbox isolates commands in Docker so even a malicious command cannot damage your host system. Use "gateway" only if Docker is unavailable.',
        optionDescriptions: {
          sandbox: 'Run commands inside an isolated Docker sandbox. Safest option.',
          gateway: 'Run commands directly on the machine hosting the gateway. Fast but less isolated.',
          node: 'Route exec to a paired Node device (e.g. your phone or another machine).',
        },
      },
      {
        path: 'tools.exec.ask',
        label: 'Exec Ask Mode',
        help: 'Whether to ask for confirmation before running commands.',
        type: 'enum',
        options: ['off', 'on-miss', 'always'],
        defaultValue: 'on-miss',
        optionDescriptions: {
          off: 'Never ask for approval — execute commands automatically.',
          'on-miss': 'Ask for approval only when the command is not in the safeBins allowlist.',
          always: 'Always ask the user to approve before running any command.',
        },
      },
      {
        path: 'tools.web.search.enabled',
        label: 'Enable Web Search',
        help: 'Allow agents to search the web.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'tools.web.search.provider',
        label: 'Search Provider',
        help: 'Which search API to use for web searches.',
        type: 'enum',
        options: ['brave', 'perplexity', 'grok'],
        defaultValue: 'brave',
      },
      {
        path: 'tools.web.search.apiKey',
        label: 'Search API Key',
        help: 'API key for the selected search provider.',
        type: 'string',
        sensitive: true,
        placeholder: 'Enter API key...',
      },
      {
        path: 'tools.web.fetch.enabled',
        label: 'Enable Web Fetch',
        help: 'Allow agents to fetch and read web page content.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'tools.web.fetch.maxChars',
        label: 'Max Fetch Characters',
        help: 'Maximum characters to extract from a fetched web page.',
        type: 'number',
        min: 1000,
        max: 500000,
        defaultValue: 50000,
      },
    ],
  },
  {
    id: 'channels',
    label: 'Channels',
    description: 'Configure messaging channel integrations (Telegram, etc.).',
    icon: '💬',
    fields: [
      {
        path: 'channels.telegram.enabled',
        label: 'Enable Telegram',
        help: 'Enable the Telegram messaging channel.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        path: 'channels.telegram.botToken',
        label: 'Telegram Bot Token',
        help: 'Bot token from @BotFather. Keep this secret.',
        type: 'string',
        sensitive: true,
        placeholder: '123456789:ABC-DEF...',
      },
      {
        path: 'channels.telegram.dmPolicy',
        label: 'DM Policy',
        help: 'Who can start a direct message conversation with the bot.',
        type: 'enum',
        options: ['pairing', 'allowlist', 'open', 'disabled'],
        defaultValue: 'pairing',
        recommended: 'pairing',
        recommendedReason: 'pairing requires senders to verify before the bot responds — prevents spam and unauthorized access. "open" is dangerous on a public bot.',
        optionDescriptions: {
          pairing: 'Unknown senders receive a pairing code. They must verify before the bot responds. Recommended.',
          allowlist: 'Only users in channels.telegram.allowFrom can DM the bot. All others are silently ignored.',
          open: 'Anyone can DM the bot without approval. Requires allowFrom: ["*"]. Use with caution.',
          disabled: 'DMs are completely disabled. The bot will not respond to any direct messages.',
        },
      },
      {
        path: 'channels.telegram.groupPolicy',
        label: 'Group Policy',
        help: 'How the bot behaves when added to group chats.',
        type: 'enum',
        options: ['open', 'disabled', 'allowlist'],
        defaultValue: 'open',
        optionDescriptions: {
          open: "Bot responds in any group it's added to.",
          disabled: 'Bot does not respond in any groups.',
          allowlist: 'Bot only responds in groups listed in channels.telegram.groups. Recommended.',
        },
      },
      {
        path: 'channels.telegram.streamMode',
        label: 'Stream Mode',
        help: 'Whether to stream partial responses as they are generated.',
        type: 'enum',
        options: ['off', 'partial', 'block'],
        defaultValue: 'partial',
        recommended: 'partial',
        recommendedReason: 'partial gives real-time "typing" feedback which feels responsive. "off" means users see nothing until the full reply is done — poor UX for longer responses.',
        optionDescriptions: {
          off: 'No streaming. Bot sends the complete reply in one message when done.',
          partial: 'Progressive streaming — bot edits the message as the reply grows. Shows live typing effect.',
          block: 'Chunked streaming — sends reply in chunks as sections complete. More readable for long responses.',
        },
      },
      {
        path: 'channels.telegram.reactionLevel',
        label: 'Reaction Level',
        help: 'How often the bot uses emoji reactions in Telegram.',
        type: 'enum',
        options: ['off', 'ack', 'minimal', 'extensive'],
        defaultValue: 'minimal',
        optionDescriptions: {
          off: 'No emoji reactions are used.',
          ack: 'React with a single acknowledgment emoji when a message is received.',
          minimal: 'Light reactions for key events (acknowledgment + completion). Default.',
          extensive: 'Rich reactions for many events including tool use, errors, thinking states.',
        },
      },
    ],
  },
  {
    id: 'commands',
    label: 'Commands',
    description: 'Control which slash commands and chat commands are registered and available.',
    icon: '⌨️',
    fields: [
      {
        path: 'commands.native',
        label: 'Register Native Commands',
        help: 'Register built-in slash commands with channels.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'commands.nativeSkills',
        label: 'Register Skill Commands',
        help: 'Register skill-provided slash commands with channels.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'commands.bash',
        label: 'Allow Bash Command',
        help: 'Allow the /bash chat command for direct shell access.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        path: 'commands.config',
        label: 'Allow /config Command',
        help: 'Allow users to view/edit config via the /config chat command.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'commands.restart',
        label: 'Allow /restart Command',
        help: 'Allow users to restart the gateway via the /restart chat command.',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'messages',
    label: 'Messages & TTS',
    description: 'Configure message behavior, TTS voice synthesis, and acknowledgement reactions.',
    icon: '🔊',
    fields: [
      {
        path: 'messages.tts.enabled',
        label: 'Enable TTS',
        help: 'Enable text-to-speech for agent responses.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        path: 'messages.tts.provider',
        label: 'TTS Provider',
        help: 'Which TTS service to use for voice synthesis.',
        type: 'enum',
        options: ['elevenlabs', 'openai', 'edge'],
        defaultValue: 'edge',
      },
      {
        path: 'messages.ackReaction',
        label: 'Ack Reaction Emoji',
        help: 'Emoji reaction to use when acknowledging received messages.',
        type: 'string',
        placeholder: '👀',
        defaultValue: '👀',
      },
      {
        path: 'messages.ackReactionScope',
        label: 'Ack Reaction Scope',
        help: 'Which message types trigger the acknowledgement reaction.',
        type: 'enum',
        options: ['group-mentions', 'group-all', 'direct', 'all'],
        defaultValue: 'group-mentions',
        optionDescriptions: {
          'group-mentions': 'Only react when directly mentioned in a group. Low noise. Default.',
          'group-all': 'React to every message in groups, not just mentions.',
          direct: 'Only react to direct messages.',
          all: 'React to everything — both groups and DMs.',
        },
      },
      {
        path: 'messages.queue.mode',
        label: 'Message Queue Mode',
        help: 'How to handle new messages that arrive while the agent is processing a previous one.',
        type: 'enum',
        options: ['steer', 'followup', 'collect', 'queue', 'interrupt'],
        defaultValue: 'followup',
        optionDescriptions: {
          steer: 'New message while processing? Steer the current response in the new direction.',
          followup: 'Queue new messages as follow-ups after the current response completes.',
          collect: 'Collect rapid messages into one batch before processing.',
          queue: 'Strict FIFO queue — process each message in order.',
          interrupt: 'New message immediately interrupts and replaces the current processing.',
        },
      },
    ],
  },
  {
    id: 'cron',
    label: 'Cron',
    description: 'Configure scheduled cron jobs.',
    icon: '⏰',
    fields: [
      {
        path: 'cron.enabled',
        label: 'Enable Cron',
        help: 'Enable the cron job scheduler.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'cron.maxConcurrentRuns',
        label: 'Max Concurrent Runs',
        help: 'Maximum number of cron jobs that can run at the same time.',
        type: 'number',
        min: 1,
        max: 20,
        defaultValue: 3,
      },
    ],
  },
  {
    id: 'session',
    label: 'Session',
    description: 'Configure conversation session scoping and idle timeout behavior.',
    icon: '🗂️',
    fields: [
      {
        path: 'session.scope',
        label: 'Session Scope',
        help: 'How session history is scoped across senders.',
        type: 'enum',
        options: ['per-sender', 'global'],
        defaultValue: 'per-sender',
        optionDescriptions: {
          'per-sender': 'Each sender gets their own isolated session. Context is private per user.',
          global: 'All senders share a single session/context. Useful for shared family/team bots.',
        },
      },
      {
        path: 'session.dmScope',
        label: 'DM Session Scope',
        help: 'How DM session history is scoped.',
        type: 'enum',
        options: ['main', 'per-peer', 'per-channel-peer', 'per-account-channel-peer'],
        defaultValue: 'main',
        optionDescriptions: {
          main: 'All DMs share one "main" session. Continuity across channels.',
          'per-peer': 'Each person gets their own session across all channels.',
          'per-channel-peer': 'Separate sessions per channel + person combo. Most isolated.',
          'per-account-channel-peer': 'Maximum isolation — separate sessions per account, channel, and person.',
        },
      },
      {
        path: 'session.idleMinutes',
        label: 'Idle Timeout (minutes)',
        help: 'Minutes of inactivity before a session is considered idle and reset.',
        type: 'number',
        min: 0,
        max: 10080,
        defaultValue: 60,
      },
    ],
  },
  {
    id: 'memory',
    label: 'Memory',
    description: 'Configure the memory backend for persistent agent knowledge.',
    icon: '🧠',
    fields: [
      {
        path: 'memory.backend',
        label: 'Memory Backend',
        help: 'Which storage backend to use for agent memory.',
        type: 'enum',
        options: ['builtin', 'qmd'],
        defaultValue: 'builtin',
        optionDescriptions: {
          builtin: "Use OpenClaw's built-in vector memory search (SQLite + embeddings). No extra setup needed.",
          qmd: 'Use QMD (external memory sidecar) for advanced multi-collection memory. Requires qmd binary.',
        },
      },
      {
        path: 'memory.citations',
        label: 'Memory Citations',
        help: 'Whether to include memory citations in agent responses.',
        type: 'enum',
        options: ['auto', 'on', 'off'],
        defaultValue: 'auto',
        optionDescriptions: {
          auto: 'Automatically add source citations when memory search finds relevant content.',
          on: 'Always add citations when memory results are injected.',
          off: 'Never add citations. Memory results are used silently.',
        },
      },
    ],
  },
  {
    id: 'browser',
    label: 'Browser',
    description: 'Configure the embedded Playwright browser for web automation.',
    icon: '🌍',
    fields: [
      {
        path: 'browser.enabled',
        label: 'Enable Browser',
        help: 'Enable the embedded browser tool for agents.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'browser.headless',
        label: 'Headless Mode',
        help: 'Run the browser without a visible window (headless).',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'browser.executablePath',
        label: 'Chrome Executable Path',
        help: 'Path to the Chrome/Chromium binary. Leave blank to use the bundled browser.',
        type: 'string',
        placeholder: '/usr/bin/google-chrome',
      },
    ],
  },
  {
    id: 'plugins',
    label: 'Plugins',
    description: 'Manage OpenClaw plugins. ChromaDB memory requires: 1) ChromaDB server running (pip install chromadb && chroma run), 2) Ollama installed (ollama.ai) with embedding model pulled (ollama pull nomic-embed-text).',
    icon: '🔌',
    fields: [
      {
        path: 'plugins.enabled',
        label: 'Enable Plugins',
        help: 'Enable the plugin system.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        path: 'plugins.allow',
        label: 'Plugin Allowlist',
        help: 'Explicit list of plugins to allow. Leave empty to allow all.',
        type: 'array',
        placeholder: 'plugin-name',
      },
      {
        path: 'plugins.deny',
        label: 'Plugin Denylist',
        help: 'Plugins to explicitly block from loading.',
        type: 'array',
        placeholder: 'plugin-name',
      },
      {
        path: 'plugins.entries.chromadb-memory.enabled',
        label: 'ChromaDB Memory: Enabled',
        help: 'Enable the ChromaDB long-term memory plugin for persistent agent knowledge storage and retrieval. Requires ChromaDB server and Ollama for embeddings.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        path: 'plugins.entries.chromadb-memory.config.chromaUrl',
        label: 'ChromaDB URL',
        help: 'URL of the ChromaDB vector database server. ChromaDB stores document embeddings for semantic search and memory retrieval. Install: pip install chromadb && chroma run --host localhost --port 8000',
        type: 'string',
        placeholder: 'http://localhost:8000',
      },
      {
        path: 'plugins.entries.chromadb-memory.config.ollamaUrl',
        label: 'Ollama URL',
        help: 'URL of the Ollama server for generating text embeddings locally. Ollama runs embedding models on your machine without sending data to external APIs. Install from ollama.ai, then run: ollama pull nomic-embed-text',
        type: 'string',
        placeholder: 'http://localhost:11434',
      },
      {
        path: 'plugins.entries.chromadb-memory.config.embeddingModel',
        label: 'Embedding Model',
        help: 'Ollama model used to convert text into vector embeddings. These embeddings enable semantic search in ChromaDB. Recommended: nomic-embed-text (fast, 768-dim) or mxbai-embed-large (higher quality, 1024-dim). Must be pulled via Ollama first.',
        type: 'string',
        placeholder: 'nomic-embed-text',
      },
      {
        path: 'plugins.entries.chromadb-memory.config.autoRecall',
        label: 'ChromaDB Auto-Recall',
        help: 'Automatically search ChromaDB for relevant memories when the agent processes messages. Retrieved context is injected into the conversation to improve responses based on past interactions and stored knowledge.',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },
];

export const ALL_FIELDS: FieldDef[] = SECTIONS.flatMap(s => s.fields);
